
-- IFRI MENTORLINK — SCHÉMA DE LA BASE DE DONNÉES
 --Groupe PIL1_2526_31
 --PostgreSQL




-- MODULE 1 : ACCOUNTS — Gestion des utilisateurs


-- Table principale des utilisateurs
CREATE TABLE "accounts_utilisateur" (
    "id"                bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "password"          varchar(128) NOT NULL,
    "last_login"        timestamp with time zone NULL,
    "is_superuser"      boolean NOT NULL,
    "nom"               varchar(100) NOT NULL,
    "prenom"            varchar(100) NOT NULL,
    "email"             varchar(254) NOT NULL UNIQUE,
    "telephone"         varchar(20) NOT NULL UNIQUE,
    "filiere"           varchar(10) NOT NULL,
    "niveau"            varchar(5) NOT NULL,
    "competences"       text NOT NULL,
    "lacunes"           text NOT NULL,
    "disponibilites"    text NOT NULL,
    "bio"               text NOT NULL,
    "photo"             varchar(100) NULL,
    "date_inscription"  timestamp with time zone NOT NULL,
    "is_active"         boolean NOT NULL,
    "is_staff"          boolean NOT NULL
);

-- Index sur email et téléphone pour les recherches rapides
CREATE INDEX "accounts_utilisateur_email_9ac6d2cb_like"
    ON "accounts_utilisateur" ("email" varchar_pattern_ops);

CREATE INDEX "accounts_utilisateur_telephone_61535039_like"
    ON "accounts_utilisateur" ("telephone" varchar_pattern_ops);

-- Table de liaison utilisateurs <-> groupes Django
CREATE TABLE "accounts_utilisateur_groups" (
    "id"                bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "utilisateur_id"    bigint NOT NULL,
    "group_id"          integer NOT NULL
);

ALTER TABLE "accounts_utilisateur_groups"
    ADD CONSTRAINT "accounts_utilisateur_gro_utilisateur_id_group_id_941da25f_uniq"
    UNIQUE ("utilisateur_id", "group_id");

ALTER TABLE "accounts_utilisateur_groups"
    ADD CONSTRAINT "accounts_utilisateur_utilisateur_id_ca92c3d8_fk_accounts_"
    FOREIGN KEY ("utilisateur_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "accounts_utilisateur_groups"
    ADD CONSTRAINT "accounts_utilisateur_groups_group_id_a4007cd2_fk_auth_group_id"
    FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "accounts_utilisateur_groups_utilisateur_id_ca92c3d8"
    ON "accounts_utilisateur_groups" ("utilisateur_id");

CREATE INDEX "accounts_utilisateur_groups_group_id_a4007cd2"
    ON "accounts_utilisateur_groups" ("group_id");

-- Table de liaison utilisateurs <-> permissions Django
CREATE TABLE "accounts_utilisateur_user_permissions" (
    "id"                bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "utilisateur_id"    bigint NOT NULL,
    "permission_id"     integer NOT NULL
);

ALTER TABLE "accounts_utilisateur_user_permissions"
    ADD CONSTRAINT "accounts_utilisateur_use_utilisateur_id_permissio_59447ab2_uniq"
    UNIQUE ("utilisateur_id", "permission_id");

ALTER TABLE "accounts_utilisateur_user_permissions"
    ADD CONSTRAINT "accounts_utilisateur_utilisateur_id_1f62d6d5_fk_accounts_"
    FOREIGN KEY ("utilisateur_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "accounts_utilisateur_user_permissions"
    ADD CONSTRAINT "accounts_utilisateur_permission_id_6f24b1cb_fk_auth_perm"
    FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "accounts_utilisateur_user_permissions_utilisateur_id_1f62d6d5"
    ON "accounts_utilisateur_user_permissions" ("utilisateur_id");

CREATE INDEX "accounts_utilisateur_user_permissions_permission_id_6f24b1cb"
    ON "accounts_utilisateur_user_permissions" ("permission_id");



-- MODULE 2 : MATCHING — Mise en correspondance


-- Demandes de mentorat (publiées par les mentorés)
CREATE TABLE "matching_demandementorat" (
    "id"                        bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "titre"                     varchar(200) NOT NULL,
    "objectif"                  text NOT NULL,
    "competences_recherchees"   text NOT NULL,
    "date_creation"             timestamp with time zone NOT NULL,
    "mentore_id"                bigint NOT NULL
);

ALTER TABLE "matching_demandementorat"
    ADD CONSTRAINT "matching_demandement_mentore_id_539e7d9e_fk_accounts_"
    FOREIGN KEY ("mentore_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "matching_demandementorat_mentore_id_539e7d9e"
    ON "matching_demandementorat" ("mentore_id");

-- Offres de mentorat (publiées par les mentors)
CREATE TABLE "matching_offrementorat" (
    "id"            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "titre"         varchar(200) NOT NULL,
    "description"   text NOT NULL,
    "competences"   text NOT NULL,
    "est_active"    boolean NOT NULL,
    "date_creation" timestamp with time zone NOT NULL,
    "mentor_id"     bigint NOT NULL
);

ALTER TABLE "matching_offrementorat"
    ADD CONSTRAINT "matching_offrementor_mentor_id_fee7a1d5_fk_accounts_"
    FOREIGN KEY ("mentor_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "matching_offrementorat_mentor_id_fee7a1d5"
    ON "matching_offrementorat" ("mentor_id");

-- Relations officielles mentor / mentoré
CREATE TABLE "matching_relationmentorat" (
    "id"            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "statut"        varchar(20) NOT NULL,
    "date_debut"    timestamp with time zone NOT NULL,
    "mentor_id"     bigint NOT NULL,
    "mentore_id"    bigint NOT NULL
);

ALTER TABLE "matching_relationmentorat"
    ADD CONSTRAINT "matching_relationmen_mentor_id_257e50a7_fk_accounts_"
    FOREIGN KEY ("mentor_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "matching_relationmentorat"
    ADD CONSTRAINT "matching_relationmen_mentore_id_d55d51ca_fk_accounts_"
    FOREIGN KEY ("mentore_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "matching_relationmentorat_mentor_id_257e50a7"
    ON "matching_relationmentorat" ("mentor_id");

CREATE INDEX "matching_relationmentorat_mentore_id_d55d51ca"
    ON "matching_relationmentorat" ("mentore_id");

-- Historique des scores de matching
CREATE TABLE "matching_historiquematching" (
    "id"            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "score"         double precision NOT NULL,
    "date_creation" timestamp with time zone NOT NULL,
    "mentor_id"     bigint NOT NULL,
    "mentore_id"    bigint NOT NULL
);

ALTER TABLE "matching_historiquematching"
    ADD CONSTRAINT "matching_historiquem_mentor_id_6af828a5_fk_accounts_"
    FOREIGN KEY ("mentor_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "matching_historiquematching"
    ADD CONSTRAINT "matching_historiquem_mentore_id_0290320a_fk_accounts_"
    FOREIGN KEY ("mentore_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "matching_historiquematching_mentor_id_6af828a5"
    ON "matching_historiquematching" ("mentor_id");

CREATE INDEX "matching_historiquematching_mentore_id_0290320a"
    ON "matching_historiquematching" ("mentore_id");



-- MODULE 3 : MESSAGING — Messagerie instantanée


-- Conversations entre utilisateurs
CREATE TABLE "messaging_conversation" (
    "id"            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "date_creation" timestamp with time zone NOT NULL
);

-- Table de liaison conversations <-> participants
CREATE TABLE "messaging_conversation_participants" (
    "id"                bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "conversation_id"   bigint NOT NULL,
    "utilisateur_id"    bigint NOT NULL
);

ALTER TABLE "messaging_conversation_participants"
    ADD CONSTRAINT "messaging_conversation_p_conversation_id_utilisat_ccf49a8f_uniq"
    UNIQUE ("conversation_id", "utilisateur_id");

ALTER TABLE "messaging_conversation_participants"
    ADD CONSTRAINT "messaging_conversati_conversation_id_890e9e37_fk_messaging"
    FOREIGN KEY ("conversation_id") REFERENCES "messaging_conversation" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "messaging_conversation_participants"
    ADD CONSTRAINT "messaging_conversati_utilisateur_id_a1e650d4_fk_accounts_"
    FOREIGN KEY ("utilisateur_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "messaging_conversation_participants_conversation_id_890e9e37"
    ON "messaging_conversation_participants" ("conversation_id");

CREATE INDEX "messaging_conversation_participants_utilisateur_id_a1e650d4"
    ON "messaging_conversation_participants" ("utilisateur_id");

-- Messages dans les conversations
CREATE TABLE "messaging_message" (
    "id"                bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "contenu"           text NOT NULL,
    "date_envoi"        timestamp with time zone NOT NULL,
    "lu"                boolean NOT NULL,
    "auteur_id"         bigint NOT NULL,
    "conversation_id"   bigint NOT NULL
);

ALTER TABLE "messaging_message"
    ADD CONSTRAINT "messaging_message_auteur_id_c6e9c1dc_fk_accounts_utilisateur_id"
    FOREIGN KEY ("auteur_id") REFERENCES "accounts_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "messaging_message"
    ADD CONSTRAINT "messaging_message_conversation_id_3db4d3d1_fk_messaging"
    FOREIGN KEY ("conversation_id") REFERENCES "messaging_conversation" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "messaging_message_auteur_id_c6e9c1dc"
    ON "messaging_message" ("auteur_id");

CREATE INDEX "messaging_message_conversation_id_3db4d3d1"
    ON "messaging_message" ("conversation_id");



-- RÉSUMÉ DES TABLES

--
-- MODULE ACCOUNTS (1 table principale + 2 tables de liaison) :
--   accounts_utilisateur                  → Utilisateurs du système
--   accounts_utilisateur_groups           → Liaison utilisateurs/groupes
--   accounts_utilisateur_user_permissions → Liaison utilisateurs/permissions
--
-- MODULE MATCHING (4 tables) :
--   matching_offrementorat      → Offres publiées par les mentors
--   matching_demandementorat    → Demandes publiées par les mentorés
--   matching_relationmentorat   → Relations officielles mentor/mentoré
--   matching_historiquematching → Historique des scores de matching
--
-- MODULE MESSAGING (3 tables) :
--   messaging_conversation              → Conversations
--   messaging_conversation_participants → Participants à chaque conversation
--   messaging_message                   → Messages échangés

