--
-- PostgreSQL database dump
--

\restrict kHmG9ejSLgYmUzyK6LrpSlegqzB3Jtnj7EVABMHB7WrTrDIqSsdX9Le0O8NQx7q

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_utilisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_utilisateur (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    telephone character varying(20) NOT NULL,
    filiere character varying(10) NOT NULL,
    niveau character varying(5) NOT NULL,
    competences text NOT NULL,
    lacunes text NOT NULL,
    disponibilites text NOT NULL,
    bio text NOT NULL,
    photo character varying(100),
    date_inscription timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL
);


ALTER TABLE public.accounts_utilisateur OWNER TO postgres;

--
-- Name: accounts_utilisateur_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_utilisateur_groups (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_utilisateur_groups OWNER TO postgres;

--
-- Name: accounts_utilisateur_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_utilisateur_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_utilisateur_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_utilisateur_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_utilisateur_user_permissions (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_utilisateur_user_permissions OWNER TO postgres;

--
-- Name: accounts_utilisateur_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_utilisateur_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_utilisateur_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: matching_demandementorat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_demandementorat (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    objectif text NOT NULL,
    competences_recherchees text NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    mentore_id bigint NOT NULL
);


ALTER TABLE public.matching_demandementorat OWNER TO postgres;

--
-- Name: matching_demandementorat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_demandementorat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_demandementorat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_demandementorat_matieres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_demandementorat_matieres (
    id bigint NOT NULL,
    demandementorat_id bigint NOT NULL,
    matiere_id bigint NOT NULL
);


ALTER TABLE public.matching_demandementorat_matieres OWNER TO postgres;

--
-- Name: matching_demandementorat_matieres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_demandementorat_matieres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_demandementorat_matieres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_historiquematching; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_historiquematching (
    id bigint NOT NULL,
    score double precision NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    mentor_id bigint NOT NULL,
    mentore_id bigint NOT NULL,
    score_filiere double precision NOT NULL,
    score_matieres double precision NOT NULL,
    score_niveau double precision NOT NULL,
    score_dispos double precision NOT NULL
);


ALTER TABLE public.matching_historiquematching OWNER TO postgres;

--
-- Name: matching_historiquematching_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_historiquematching ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_historiquematching_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_matiere; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_matiere (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    categorie character varying(20) DEFAULT 'autre'::character varying
);


ALTER TABLE public.matching_matiere OWNER TO postgres;

--
-- Name: matching_matiere_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_matiere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_matiere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_offrementorat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_offrementorat (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    description text NOT NULL,
    competences text NOT NULL,
    est_active boolean NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    mentor_id bigint NOT NULL
);


ALTER TABLE public.matching_offrementorat OWNER TO postgres;

--
-- Name: matching_offrementorat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_offrementorat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_offrementorat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_offrementorat_matieres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_offrementorat_matieres (
    id bigint NOT NULL,
    offrementorat_id bigint NOT NULL,
    matiere_id bigint NOT NULL
);


ALTER TABLE public.matching_offrementorat_matieres OWNER TO postgres;

--
-- Name: matching_offrementorat_matieres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_offrementorat_matieres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_offrementorat_matieres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_relationmentorat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_relationmentorat (
    id bigint NOT NULL,
    statut character varying(20) NOT NULL,
    date_debut timestamp with time zone NOT NULL,
    mentor_id bigint NOT NULL,
    mentore_id bigint NOT NULL
);


ALTER TABLE public.matching_relationmentorat OWNER TO postgres;

--
-- Name: matching_relationmentorat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_relationmentorat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_relationmentorat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messaging_conversation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messaging_conversation (
    id bigint NOT NULL,
    date_creation timestamp with time zone NOT NULL
);


ALTER TABLE public.messaging_conversation OWNER TO postgres;

--
-- Name: messaging_conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messaging_conversation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messaging_conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messaging_conversation_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messaging_conversation_participants (
    id bigint NOT NULL,
    conversation_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL
);


ALTER TABLE public.messaging_conversation_participants OWNER TO postgres;

--
-- Name: messaging_conversation_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messaging_conversation_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messaging_conversation_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messaging_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messaging_message (
    id bigint NOT NULL,
    contenu text NOT NULL,
    date_envoi timestamp with time zone NOT NULL,
    lu boolean NOT NULL,
    auteur_id bigint NOT NULL,
    conversation_id bigint NOT NULL
);


ALTER TABLE public.messaging_message OWNER TO postgres;

--
-- Name: messaging_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messaging_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messaging_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_utilisateur accounts_utilisateur_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_email_key UNIQUE (email);


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_gro_utilisateur_id_group_id_941da25f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_gro_utilisateur_id_group_id_941da25f_uniq UNIQUE (utilisateur_id, group_id);


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_utilisateur accounts_utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_pkey PRIMARY KEY (id);


--
-- Name: accounts_utilisateur accounts_utilisateur_telephone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_telephone_key UNIQUE (telephone);


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_use_utilisateur_id_permissio_59447ab2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_use_utilisateur_id_permissio_59447ab2_uniq UNIQUE (utilisateur_id, permission_id);


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: matching_demandementorat_matieres matching_demandementorat_demandementorat_id_matie_e44fc9a3_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_demandementorat_matieres
    ADD CONSTRAINT matching_demandementorat_demandementorat_id_matie_e44fc9a3_uniq UNIQUE (demandementorat_id, matiere_id);


--
-- Name: matching_demandementorat_matieres matching_demandementorat_matieres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_demandementorat_matieres
    ADD CONSTRAINT matching_demandementorat_matieres_pkey PRIMARY KEY (id);


--
-- Name: matching_demandementorat matching_demandementorat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_demandementorat
    ADD CONSTRAINT matching_demandementorat_pkey PRIMARY KEY (id);


--
-- Name: matching_historiquematching matching_historiquematching_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_historiquematching
    ADD CONSTRAINT matching_historiquematching_pkey PRIMARY KEY (id);


--
-- Name: matching_matiere matching_matiere_nom_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_matiere
    ADD CONSTRAINT matching_matiere_nom_key UNIQUE (nom);


--
-- Name: matching_matiere matching_matiere_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_matiere
    ADD CONSTRAINT matching_matiere_pkey PRIMARY KEY (id);


--
-- Name: matching_offrementorat_matieres matching_offrementorat_m_offrementorat_id_matiere_876339ef_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_offrementorat_matieres
    ADD CONSTRAINT matching_offrementorat_m_offrementorat_id_matiere_876339ef_uniq UNIQUE (offrementorat_id, matiere_id);


--
-- Name: matching_offrementorat_matieres matching_offrementorat_matieres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_offrementorat_matieres
    ADD CONSTRAINT matching_offrementorat_matieres_pkey PRIMARY KEY (id);


--
-- Name: matching_offrementorat matching_offrementorat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_offrementorat
    ADD CONSTRAINT matching_offrementorat_pkey PRIMARY KEY (id);


--
-- Name: matching_relationmentorat matching_relationmentorat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_relationmentorat
    ADD CONSTRAINT matching_relationmentorat_pkey PRIMARY KEY (id);


--
-- Name: messaging_conversation_participants messaging_conversation_p_conversation_id_utilisat_ccf49a8f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_conversation_participants
    ADD CONSTRAINT messaging_conversation_p_conversation_id_utilisat_ccf49a8f_uniq UNIQUE (conversation_id, utilisateur_id);


--
-- Name: messaging_conversation_participants messaging_conversation_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_conversation_participants
    ADD CONSTRAINT messaging_conversation_participants_pkey PRIMARY KEY (id);


--
-- Name: messaging_conversation messaging_conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_conversation
    ADD CONSTRAINT messaging_conversation_pkey PRIMARY KEY (id);


--
-- Name: messaging_message messaging_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_message
    ADD CONSTRAINT messaging_message_pkey PRIMARY KEY (id);


--
-- Name: accounts_utilisateur_email_9ac6d2cb_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_utilisateur_email_9ac6d2cb_like ON public.accounts_utilisateur USING btree (email varchar_pattern_ops);


--
-- Name: accounts_utilisateur_groups_group_id_a4007cd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_utilisateur_groups_group_id_a4007cd2 ON public.accounts_utilisateur_groups USING btree (group_id);


--
-- Name: accounts_utilisateur_groups_utilisateur_id_ca92c3d8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_utilisateur_groups_utilisateur_id_ca92c3d8 ON public.accounts_utilisateur_groups USING btree (utilisateur_id);


--
-- Name: accounts_utilisateur_telephone_61535039_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_utilisateur_telephone_61535039_like ON public.accounts_utilisateur USING btree (telephone varchar_pattern_ops);


--
-- Name: accounts_utilisateur_user_permissions_permission_id_6f24b1cb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_utilisateur_user_permissions_permission_id_6f24b1cb ON public.accounts_utilisateur_user_permissions USING btree (permission_id);


--
-- Name: accounts_utilisateur_user_permissions_utilisateur_id_1f62d6d5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_utilisateur_user_permissions_utilisateur_id_1f62d6d5 ON public.accounts_utilisateur_user_permissions USING btree (utilisateur_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: matching_demandementorat_matieres_demandementorat_id_7e170a68; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_demandementorat_matieres_demandementorat_id_7e170a68 ON public.matching_demandementorat_matieres USING btree (demandementorat_id);


--
-- Name: matching_demandementorat_matieres_matiere_id_485bedd3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_demandementorat_matieres_matiere_id_485bedd3 ON public.matching_demandementorat_matieres USING btree (matiere_id);


--
-- Name: matching_demandementorat_mentore_id_539e7d9e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_demandementorat_mentore_id_539e7d9e ON public.matching_demandementorat USING btree (mentore_id);


--
-- Name: matching_historiquematching_mentor_id_6af828a5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_historiquematching_mentor_id_6af828a5 ON public.matching_historiquematching USING btree (mentor_id);


--
-- Name: matching_historiquematching_mentore_id_0290320a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_historiquematching_mentore_id_0290320a ON public.matching_historiquematching USING btree (mentore_id);


--
-- Name: matching_matiere_nom_a2aa2562_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_matiere_nom_a2aa2562_like ON public.matching_matiere USING btree (nom varchar_pattern_ops);


--
-- Name: matching_offrementorat_matieres_matiere_id_02223384; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_offrementorat_matieres_matiere_id_02223384 ON public.matching_offrementorat_matieres USING btree (matiere_id);


--
-- Name: matching_offrementorat_matieres_offrementorat_id_33b7381b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_offrementorat_matieres_offrementorat_id_33b7381b ON public.matching_offrementorat_matieres USING btree (offrementorat_id);


--
-- Name: matching_offrementorat_mentor_id_fee7a1d5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_offrementorat_mentor_id_fee7a1d5 ON public.matching_offrementorat USING btree (mentor_id);


--
-- Name: matching_relationmentorat_mentor_id_257e50a7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_relationmentorat_mentor_id_257e50a7 ON public.matching_relationmentorat USING btree (mentor_id);


--
-- Name: matching_relationmentorat_mentore_id_d55d51ca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matching_relationmentorat_mentore_id_d55d51ca ON public.matching_relationmentorat USING btree (mentore_id);


--
-- Name: messaging_conversation_participants_conversation_id_890e9e37; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX messaging_conversation_participants_conversation_id_890e9e37 ON public.messaging_conversation_participants USING btree (conversation_id);


--
-- Name: messaging_conversation_participants_utilisateur_id_a1e650d4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX messaging_conversation_participants_utilisateur_id_a1e650d4 ON public.messaging_conversation_participants USING btree (utilisateur_id);


--
-- Name: messaging_message_auteur_id_c6e9c1dc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX messaging_message_auteur_id_c6e9c1dc ON public.messaging_message USING btree (auteur_id);


--
-- Name: messaging_message_conversation_id_3db4d3d1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX messaging_message_conversation_id_3db4d3d1 ON public.messaging_message USING btree (conversation_id);


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_groups_group_id_a4007cd2_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_groups_group_id_a4007cd2_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_permission_id_6f24b1cb_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_permission_id_6f24b1cb_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_utilisateur_id_1f62d6d5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_utilisateur_id_1f62d6d5_fk_accounts_ FOREIGN KEY (utilisateur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_utilisateur_id_ca92c3d8_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_utilisateur_id_ca92c3d8_fk_accounts_ FOREIGN KEY (utilisateur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_utilisateur_id FOREIGN KEY (user_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_demandementorat_matieres matching_demandement_demandementorat_id_7e170a68_fk_matching_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_demandementorat_matieres
    ADD CONSTRAINT matching_demandement_demandementorat_id_7e170a68_fk_matching_ FOREIGN KEY (demandementorat_id) REFERENCES public.matching_demandementorat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_demandementorat_matieres matching_demandement_matiere_id_485bedd3_fk_matching_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_demandementorat_matieres
    ADD CONSTRAINT matching_demandement_matiere_id_485bedd3_fk_matching_ FOREIGN KEY (matiere_id) REFERENCES public.matching_matiere(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_demandementorat matching_demandement_mentore_id_539e7d9e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_demandementorat
    ADD CONSTRAINT matching_demandement_mentore_id_539e7d9e_fk_accounts_ FOREIGN KEY (mentore_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_historiquematching matching_historiquem_mentor_id_6af828a5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_historiquematching
    ADD CONSTRAINT matching_historiquem_mentor_id_6af828a5_fk_accounts_ FOREIGN KEY (mentor_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_historiquematching matching_historiquem_mentore_id_0290320a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_historiquematching
    ADD CONSTRAINT matching_historiquem_mentore_id_0290320a_fk_accounts_ FOREIGN KEY (mentore_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_offrementorat_matieres matching_offrementor_matiere_id_02223384_fk_matching_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_offrementorat_matieres
    ADD CONSTRAINT matching_offrementor_matiere_id_02223384_fk_matching_ FOREIGN KEY (matiere_id) REFERENCES public.matching_matiere(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_offrementorat matching_offrementor_mentor_id_fee7a1d5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_offrementorat
    ADD CONSTRAINT matching_offrementor_mentor_id_fee7a1d5_fk_accounts_ FOREIGN KEY (mentor_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_offrementorat_matieres matching_offrementor_offrementorat_id_33b7381b_fk_matching_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_offrementorat_matieres
    ADD CONSTRAINT matching_offrementor_offrementorat_id_33b7381b_fk_matching_ FOREIGN KEY (offrementorat_id) REFERENCES public.matching_offrementorat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_relationmentorat matching_relationmen_mentor_id_257e50a7_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_relationmentorat
    ADD CONSTRAINT matching_relationmen_mentor_id_257e50a7_fk_accounts_ FOREIGN KEY (mentor_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_relationmentorat matching_relationmen_mentore_id_d55d51ca_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_relationmentorat
    ADD CONSTRAINT matching_relationmen_mentore_id_d55d51ca_fk_accounts_ FOREIGN KEY (mentore_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: messaging_conversation_participants messaging_conversati_conversation_id_890e9e37_fk_messaging; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_conversation_participants
    ADD CONSTRAINT messaging_conversati_conversation_id_890e9e37_fk_messaging FOREIGN KEY (conversation_id) REFERENCES public.messaging_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: messaging_conversation_participants messaging_conversati_utilisateur_id_a1e650d4_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_conversation_participants
    ADD CONSTRAINT messaging_conversati_utilisateur_id_a1e650d4_fk_accounts_ FOREIGN KEY (utilisateur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: messaging_message messaging_message_auteur_id_c6e9c1dc_fk_accounts_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_message
    ADD CONSTRAINT messaging_message_auteur_id_c6e9c1dc_fk_accounts_utilisateur_id FOREIGN KEY (auteur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: messaging_message messaging_message_conversation_id_3db4d3d1_fk_messaging; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaging_message
    ADD CONSTRAINT messaging_message_conversation_id_3db4d3d1_fk_messaging FOREIGN KEY (conversation_id) REFERENCES public.messaging_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict kHmG9ejSLgYmUzyK6LrpSlegqzB3Jtnj7EVABMHB7WrTrDIqSsdX9Le0O8NQx7q

