# Generated by Django 6.0.6 on 2026-06-07 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('objectif', models.TextField()),
                ('competences_recherchees', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_mentorat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_en_tant_que_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_en_tant_que_mentore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffreMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('competences', models.TextField(help_text='Liste des compétences séparées par des virgules')),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_mentorat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelationMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_mentore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
