# Generated by Django 6.0.6 on 2026-06-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('info', 'Informatique'), ('math', 'Mathématiques'), ('reseau', 'Réseaux'), ('bd', 'Bases de données'), ('dev', 'Développement'), ('ia', 'Intelligence Artificielle'), ('securite', 'Sécurité'), ('autre', 'Autre')], default='autre', max_length=20)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='historiquematching',
            name='score_filiere',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historiquematching',
            name='score_matieres',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historiquematching',
            name='score_niveau',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='demandementorat',
            name='competences_recherchees',
            field=models.TextField(blank=True, help_text='Compétences supplémentaires recherchées'),
        ),
        migrations.AlterField(
            model_name='offrementorat',
            name='competences',
            field=models.TextField(blank=True, help_text='Compétences supplémentaires'),
        ),
        migrations.AddField(
            model_name='demandementorat',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='demandes', to='matching.matiere'),
        ),
        migrations.AddField(
            model_name='offrementorat',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='offres', to='matching.matiere'),
        ),
    ]
