# Generated by Django 6.0.6 on 2026-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matiere_historiquematching_score_filiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='categorie',
        ),
    ]
