# Generated by Django 6.0.6 on 2026-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matiere_historiquematching_score_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='categorie',
            field=models.CharField(choices=[('info', 'Informatique générale'), ('math', 'Mathématiques'), ('reseau', 'Réseaux'), ('bd', 'Bases de données'), ('dev', 'Développement'), ('ia', 'Intelligence Artificielle'), ('securite', 'Sécurité'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
