# Generated by Django 6.0.6 on 2026-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_matiere_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquematching',
            name='score_dispos',
            field=models.FloatField(default=0),
        ),
    ]
